require("config.plugin_config.gruvbox")
require("config.plugin_config.lualine")
require("config.plugin_config.nvim-tree")
require("config.plugin_config.treesitter")
require("config.plugin_config.telescope")
require("config.plugin_config.format")
